version: '3'
services:
  actuator-server:
    environment:
      - DOCKER_PORT=8888
      - DOCKER_AC_SERVER=http://actuator-server:8888
      - DOCKER_AC_CLIENT=http://actuator-server:8888
    build:
      context: ./docker-actuator-server
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
  actuator-client-1:
    environment:
      - DOCKER_PORT=8080
      - DOCKER_AC_SERVER=http://actuator-server:8888
      - DOCKER_AC_CLIENT=http://actuator-client-1:8080
    build:
      context: ./docker-actuator-client
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
  actuator-client-2:
    environment:
      - DOCKER_PORT=8081
      - DOCKER_AC_SERVER=http://actuator-server:8888
      - DOCKER_AC_CLIENT=http://actuator-client-2:8081
    build:
      context: ./docker-actuator-client
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
  actuator-client-multi:
    environment:
      - DOCKER_PORT=8082
      - DOCKER_AC_SERVER=http://actuator-server:8888
      - DOCKER_AC_CLIENT=http://actuator-client-multi:8082
    build:
      context: ./docker-actuator-client-multi
      dockerfile: Dockerfile
    ports:
      - '8082:8082'